version: '3'

services:
    server:
        image: schal/vrf-server-example
        ports:
            - "5000:5000"
        volumes:
            - ./server_image/test_data/params.json:/data/params.json
    mixserver1:
        image: schal/vrf-mix-server
        ports:
            - "8041:8041"
            - "8000:8000"
        environment:
            - SERVER=server:5000
            - IP=mixserver1
            - PORT=8000
            - PORT_A=8041
            - PORT_B=4041
            - MIXSERVER_NAME=01
        depends_on:
            - server
    mixserver2:
        image: schal/vrf-mix-server
        ports:
            - "8042:8042"
            - "8050:8050"
        environment:
            - SERVER=server:5000
            - IP=mixserver2
            - PORT=8050
            - PORT_A=8042
            - PORT_B=4042
            - MIXSERVER_NAME=02
        depends_on:
            - server
    mixserver3:
        image: schal/vrf-mix-server
        ports:
            - "8043:8043"
            - "9000:9000"
        environment:
            - SERVER=server:5000
            - IP=mixserver3
            - PORT=9000
            - PORT_A=8043
            - PORT_B=4043
            - MIXSERVER_NAME=03
        depends_on:
            - server
